### PR TITLE
4/8 tests are done, some problems with attributes

### PR DESCRIPTION
**Pull request by YaroslavYarynych**
- [DEMO LINK](https://YaroslavYarynych.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://YaroslavYarynych.github.io/layout_moyo-header/report/html_report/)

### CODE REVIEW

**Review by superpooperxxx — CHANGES_REQUESTED** [review]
Hey, good job🔥 But all tests need to be passed.
1. Try removing `text-decoration` on links. This way tests should pass.
2. Format your html according to [this](https://yaroslavyarynych.github.io/layout_moyo-header/)

**Comment by YaroslavYarynych** [comment]
I spoke with Oleksandr on QnA session, we can`t fix it. Troubles with references. Also Oleksandra said, that if code is okay, I can write here and continue doing next tasks. Code is okay, we have checked it.

**Review by Oleksandr-kopaevich — APPROVED** [review]
Well done, we can ignore those 4 failed tests as they are falsy.

**Comment by YaroslavYarynych** [comment]
Thank you! I appreciate it!

**Pull request closed without merging**
