### PR TITLE
add changes the readme.md

### PR DESCRIPTION
**Pull request by AlexShura85**
- [DEMO LINK](https://AlexShura85.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://AlexShura85.github.io/layout_moyo-header/report/html_report/)
 - [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] **CSS Variable** is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

### CODE REVIEW

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Seems like the task was not completed. Please push your changes and deploy them. 

If you have any questions - feel free to ask them in fe_chat

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Please implement header according to design. If you have any questions feel free to ask in fe_chat 
image

**Comment by AlexShura85** [comment]
> Please implement header according to design. If you have any questions feel free to ask in fe_chat image

**Comment by AlexShura85** [comment]
@nazarmatsevych hi) could you check my pull request again? thanks)

**Review by l4st1m0za — APPROVED** [review]
Good job!

**Pull request closed without merging**
