### PR TITLE
Creating header

### PR DESCRIPTION
**Pull request by DominoSl**
- [DEMO LINK](https://DominoSl.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DominoSl.github.io/layout_moyo-header/report/html_report/)

### CODE REVIEW

**Review by danylo-onishchuk — APPROVED** [review]
good job!

**Comment by Pedro-Dev100** [comment]
Criado pull request

**Comment by Pedro-Dev100** [comment]
Criado um pull request

**Comment by Pedro-Dev100** [comment]
@[

**Comment by Detek-tor** [comment]
- [DEMO LINK](https://detek-tor.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://detek-tor.github.io/layout_moyo-header/report/html_report/)

**Comment by sam-steph** [comment]
Replace `<sam-steph>` with your Github username and copy the links to Pull Request description:
- [DEMO LINK](https://sam-steph.github.io/layout_hello-world/)
- [TEST REPORT LINK]( https://sam-steph.github.io/layout_hello-world/report/html_report/)

**Comment by KOliinyk** [comment]
- [DEMO LINK](https://KOliinyk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://KOliinyk.github.io/layout_moyo-header/report/html_report/)

**Comment by DjSerji** [comment]
- [DEMO LINK](https://DjSerji.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DjSerji.github.io/layout_moyo-header/report/html_report/)

**Comment by DjSerji** [comment]
- [DEMO LINK](https://DjSerji.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DjSerji.github.io/layout_moyo-header/report/html_report/)

- [х] Header height is set in 1 place (for the links)
- [х] Content is vertically centered (for any header height)
- [х] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [х] Logo is an image wrapped with a link
- [х] **CSS Variable** is used for a blue color
- [х] Pseudo-element is used for a blue line below the active link
- [х] Code follows all the [Code Style Rules ❗️](./checklist.md)

**Comment by petro-fox** [comment]
- [DEMO LINK](https://petro-fox.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://petro-fox.github.io/layout_moyo-header/report/html_report/)

**Comment by NataliiaCode** [comment]
- [DEMO LINK](https://NataliiaCode.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://NataliiaCode.github.io/layout_moyo-header/report/html_report/)

**Comment by ihnatd** [comment]
- [DEMO LINK](https://ihnatd.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ihnatd.github.io/layout_moyo-header/report/html_report/)

**Comment by Bukavyna** [comment]
- [DEMO LINK](https://Bukavyna.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Bukavyna.github.io/layout_moyo-header/report/html_report/)

**Comment by Bukavyna** [comment]
The and

**Comment by Bukavyna** [comment]
- [DEMO LINK](https://Bukavyna.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Bukavyna.github.io/layout_moyo-header/report/html_report/)

**Comment by aakash1sadhu** [comment]
- [DEMO LINK](https://aakash1sadhu.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://aakash1sadhu.github.io/layout_moyo-header/report/html_report/)

**Comment by Marsol0** [comment]
- [DEMO LINK](https://Marsol0.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Marsol0.github.io/layout_moyo-header/report/html_report/)

**Comment by 230220** [comment]
[DEMO LINK](https://230220.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://230220.github.io/layout_moyo-header/report/html_report/)

**Comment by souzasfelipe** [comment]
develop

**Comment by Yurii-Nedzelnytskyi** [comment]
Hi

**Comment by kdanylo90** [comment]
- [DEMO LINK](https://kdanylo90.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://kdanylo90.github.io/layout_hello-world/report/html_report/)

**Comment by kdanylo90** [comment]
- [DEMO LINK](https://kdanylo90.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://kdanylo90.github.io/layout_moyo-header/report/html_report/)

**Comment by matheuzin-cry** [comment]
- [DEMO LINK](https://matheuzin-cry.github.io/layout_moyo-header/)
- - [TEST REPORT LINK](https://matheuzin-cry.github.io/layout_moyo-header/report/html_report/)

**Comment by Ostik87** [comment]
[DEMO LINK](https://Ostik87.github.io/layout_moyo-header/)

[TEST REPORT LINK](https://Ostik87.github.io/layout_moyo-header/report/html_report/)

**Pull request closed without merging**
