### PR TITLE
made task 'MOYO Header'

### PR DESCRIPTION
**Pull request by TKuts**
- [DEMO LINK](https://tkuts.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://tkuts.github.io/layout_moyo-header/report/html_report/)

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
About your questions - looks like you made right solution for is-active link and hover.
But i can't to see demo links.
They are not work.
Please check them and check comments. Maybe deploy after fixes coments will fix links.

**Comment by TKuts** [comment]
- [DEMO LINK](https://tkuts.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://tkuts.github.io/layout_moyo-header/report/html_report/)

**Comment by TKuts** [comment]
I made a new merge.

**Comment by TKuts** [comment]
- [DEMO LINK](https://tkuts.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://tkuts.github.io/layout_moyo-header/report/html_report/)

**Pull request closed without merging**
