### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by dima91020**

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
add links to PR description

**Comment by dima91020** [comment]
> add links to PR description

**Comment by dima91020** [comment]
[DEMO LINK](https://dima91020.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://dima91020.github.io/layout_moyo-header/report/html_report/)

**Comment by dima91020** [comment]
[DEMO LINK](https://dima91020.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://dima91020.github.io/layout_moyo-header/report/html_report/)

**Pull request closed without merging**
