### PR TITLE
adding index.html

### PR DESCRIPTION
**Pull request by Anastasiia-Tatarchenko**

### CODE REVIEW

**Comment by Anastasiia-Tatarchenko** [comment]
- [DEMO LINK](https://Anastasiia-Tatarchenko.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Anastasiia-Tatarchenko.github.io/layout_moyo-header/report/html_report/)

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
You need to stretch the header to the full width of the browser window and you also need to run your code, because now there is nothing in PR
image

**Comment by Anastasiia-Tatarchenko** [comment]
- [DEMO LINK](https://Anastasiia-Tatarchenko.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Anastasiia-Tatarchenko.github.io/layout_moyo-header/report/html_report/)

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
I still can't see your changes, please push them :)
image

Also remove max-width rule to fixed previous comment
image


If you have any questions - feel free to ask them in fe_chat

**Pull request closed without merging**
