### PR TITLE
create-moyo-header

### PR DESCRIPTION
**Pull request by Kuper18**

### CODE REVIEW

**Review by polosanya — CHANGES_REQUESTED** [review]
Hi! I am your mentor, hope we will have useful and productive cooperation) :handshake:
Here are some comments that would be great to fix to improve your code:
- First of all, please add demo and test links to the PR description, so mentors can easily find it
image

**Review by Kuper18 — COMMENTED** [review]
Hi, nice to meet you! I've already redone my code. Thanks for advice
Here is a demo link:
https://kuper18.github.io/layout_moyo-header/

**Review by Kuper18 — COMMENTED** [review]
Hi! Is it possible to make a new fork for this challenge on the platform, I thought you will receive some auto notification about my changes, and no one checks it, and I wanted to recreate a pull request, and decided to remove my repository to make a new fork on the platform and so on. It was a huge mistake. Could you help me with this issue? Or should I just create a new pull request?

**Comment by polosanya** [comment]
Hi! Usually, it's enough to re-request the review after a new commit. 
https://mate-academy.github.io/layout_task-guideline/#to-update-you-pr-repeat-steps-13-18-no-need-to-create-the-pr-one-more-time.
You can create a new Pull Request or delete the repository with this task and fork it again. If you have any difficulties, it's better to ask questions in your personal/group chat in Slack and tag mentors to get the answers quickly

**Pull request closed without merging**
