### PR TITLE
moyo_header

### PR DESCRIPTION
**Pull request by stnayn**
- [DEMO LINK](https://stnayn.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://stnayn.github.io/layout_moyo-header/report/html_report/)

### CODE REVIEW

**Comment by sTorba24** [comment]
Open a pr please to be able to review

**Comment by OlEzhA0** [comment]
Hey! Open your PR pls

**Comment by stnayn** [comment]
> Hey! Open your PR pls

https://github.com/mate-academy/layout_moyo-header/pull/2756

**Review by OleziO — COMMENTED** [review]
Please open PR for review.

**Comment by stnayn** [comment]
> Please open PR for review.


This PR is closed, the correct one has already been verified, it can be found at the link: https://github.com/mate-academy/layout_moyo-header/pull/2756

**Comment by stnayn** [comment]
If you have any advice on what I should do with this PR, please write

**Pull request closed without merging**
